# Server
server.port=8081

# Spring Application
spring.application.name=auth-service

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=paystream
spring.datasource.password=paystream_local
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=paystream-super-secret-key-min-256-bits-change-this-in-production-please
jwt.access-token-expiry-ms=900000
jwt.refresh-token-expiry-days=7

# Management / Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized